spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    open-in-view: true




